site_name: Warestack Dataroom
theme: 
  icon:
    annotation: material/plus-circle
  name: material
  logo: assets/images/stack.svg
  favicon: assets/images/favicon.ico
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.footnote.tooltips

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/warestack
    - icon: fontawesome/brands/twitter
      link: https://github.com/warestack
    - icon: fontawesome/brands/linkedin
      link: https://github.com/warestack

plugins:
  - termynal
  - search:
      lang: en

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.superfences 
copyright: |
  &copy; 2023 <a href="https://www.warestack.com"  target="_blank" rel="noopener">Warestack </a>
  

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/warestack
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/36080416
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/pqg5sxhx6Y
    